### ISSUE TITLE
must be set by the webdriver.gecko.driver system property

### ISSUE THREAD

**Issue by wuxiansen** [tarun3kumar/seleniumtestsframework#13]
use firefox on mac system, need  webdriver.gecko.driver [geckodriver](https://github.com/mozilla/geckodriver/releases)
```
java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases

	at com.google.common.base.Preconditions.checkState(Preconditions.java:200)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:109)
	at org.openqa.selenium.firefox.GeckoDriverService.access$000(GeckoDriverService.java:37)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:95)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:296)
	at org.openqa.selenium.firefox.FirefoxDriver.createCommandExecutor(FirefoxDriver.java:277)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:135)
	at com.seleniumtests.browserfactory.FirefoxDriverFactory.createNativeDriver(FirefoxDriverFactory.java:40)
	at com.seleniumtests.browserfactory.FirefoxDriverFactory.createWebDriverWithTimeout(FirefoxDriverFactory.java:72)
	at com.seleniumtests.browserfactory.FirefoxDriverFactory.createWebDriver(FirefoxDriverFactory.java:48)
	at com.seleniumtests.driver.WebUIDriver.createRemoteWebDriver(WebUIDriver.java:183)
	at com.seleniumtests.driver.WebUIDriver.createWebDriver(WebUIDriver.java:213)
	at com.seleniumtests.webelements.PageObject.open(PageObject.java:388)
	at com.seleniumtests.webelements.PageObject.<init>(PageObject.java:99)
	at com.seleniumtests.webpage.RegistrationPage.<init>(RegistrationPage.java:49)
	at com.seleniumtests.tests.RegistrationTest.registerWithValidUserData(RegistrationTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by AngryTester** [comment]
u must set system property,like this:

`System.setProperty("webdriver.gecko.driver", ("src/main/resources/geckodriver").toString());`
